### PR TITLE
Add script to fix package json from build step

### LINKED ISSUE #405: [BUG]: dist-types/index.d.ts is not present in the published NPM package
### What happened?

Hey awesome maintainers! After upgrading from 4.1.1 to 4.1.2 I noticed the following tsc error:
```shell
 error TS7016: Could not find a declaration file for module '@octokit/plugin-retry'. '/some-path-here/node_modules/.pnpm/@octokit+plugin-retry@4.1.2_@octokit+core@4.2.0/node_modules/@octokit/plugin-retry/dist-node/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/octokit__plugin-retry` if it exists or add a new declaration (.d.ts) file containing `declare module '@octokit/plugin-retry';`

2 import { retry } from '@octokit/plugin-retry';
```
Having a look in the tgz on npm I only see a `dist-node` directory, but the package.json exports the types in `dist-types/index.d.ts`

### Versions

"@octokit/core": "4.2.0"
"@octokit/plugin-retry": "4.1.2",
"@octokit/rest": "19.0.7",
node 16.19.1

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by oscard0m**
Resolves #405

----

### Before the change?

The released npm package is missing most of the files generated by the build step. `dist-node`, `dist-types`, `dist-web`... even though they are generated correctly.

You can read more about my explanation in the linked issue.

### After the change?

I expected npm to read the file patterns correctly so we publish all the necessary files again.

### Other information
This is a mix of an issue with `npm@v9` (https://github.com/npm/cli/issues/6164) and the fact we rely on `pika` for the build step. Pika has been archived [since April 2022](https://github.com/FredKSchott/pika-pack) so there is nothing we can do with Pika.

I'm opening a discussion to discuss what we should do: https://github.com/octokit/octokit.js/discussions/2403

## Open questions

If we agree on this solution, we need to plan:
- How to merge and release this?
- What do we do with the rest of the repositories?
- What do we do with the already published versions with missing files?

----

### Pull request checklist
Because this is kind of a temporary hack, do you think I should add tests + documentation for this?

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?
No

### Pull request type
Because of the problems is giving to users, I'm treating it as a bug: `Type: Bug`. In terms of semantic commit, let me know if I need to change `ci()` to `fix()`

----

### CODE REVIEW

File: scripts/fix-package-json.js [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
+
+pkg.files = pkg.files.map((file) => {
+  if (file.endsWith("/")) {
+    return file + "**";
+  }
+  return file;
+});
+
+fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2), "utf8");
```
Comment (wolfy1339) [inline scripts/fix-package-json.js:14]: Missing EOF newline

**Review by wolfy1339 — APPROVED** [review]
LGTM only one small code style issue

**Comment by oscard0m** [comment]
> LGTM only one small code style issue

- How to merge and release this?
- What do we do with the rest of the repositories?
- What do we do with the already published versions with missing files?

**Comment by wolfy1339** [comment]
> - How to merge and release this?
Merge this as a bugfix release

> - What do we do with the rest of the repositories?

I suppose we would need to apply the fix there as well

> - What do we do with the already published versions with missing files?

Those versions could be marked as deprecated

File: scripts/fix-package-json.js [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
+
+pkg.files = pkg.files.map((file) => {
+  if (file.endsWith("/")) {
+    return file + "**";
+  }
+  return file;
+});
+
+fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + EOL, "utf8");
```
Comment (wolfy1339) [inline scripts/fix-package-json.js:15]: Missing the new line here

Comment (oscard0m) [reply scripts/fix-package-json.js:15]: > Missing the new line here

Can you elaborate?

I thought I covered that with `EOL`.

Comment (wolfy1339) [reply scripts/fix-package-json.js:15]: At the end of the code file itself, not I'm the call to `fs.write()`

**Review by wolfy1339 — APPROVED** [review]

**Comment by wolfy1339** [comment]
@oscard0m Can you run this through an octoherd script to apply this to all the repositories? Until we get esbuild done so releases aren't broken.

The following repos had recent releases:
- `@octokit/app`
- `@octokit/oauth-app`

**Comment by oscard0m** [comment]
> @oscard0m Can you run this through an octoherd script to apply this to all the repositories? Until we get esbuild done so releases aren't broken.
> 
> The following repos had recent releases:
> 
> * `@octokit/app`
> * `@octokit/oauth-app`

Sure! I will try to make some time during the weekend, but I'm unsure if I can. I'll keep you posted.

**Comment by oscard0m** [comment]
@wolfy1339 Created manual PRs for these two repos to remove friction:
- https://github.com/octokit/app.js/pull/417
- https://github.com/octokit/oauth-app.js/pull/411
